### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: substr_replace(): Argument #1 ($string) must be of type array|string, null given

### ISSUE THREAD

**Issue by M3ndes** [maurobonfietti/slim4-api-skeleton-crud-generator#20]
PHP Fatal error:  Uncaught TypeError: substr_replace(): Argument #1 ($string) must be of type array|string, null given in /home/thales/projects/slim-php/vendor/maurobonfietti/skel-api-slim-php-crud-generator/src/Command/CrudGeneratorService.php:62

Hi, do you have any idea to what the erro above could be?
I have created the database already.

**Comment by maurobonfietti** [comment]
Hi @M3ndes !

Mmm, I'm not sure...
What command are you running?
Are you using MySQL? What Version?
Could you try again with another `table` for example?

**Comment by M3ndes** [comment]
mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))

./console api:generate:endpoints player

my table has a id and a name only. 

it works only if i commet the line 62, 
$this->postParams = substr_replace($this->list6, '', -14)

i also have tried with another table but the error stills

**Comment by maurobonfietti** [comment]
I'm executing the same command with a table `player` with a structure like this:

```sql
CREATE TABLE `player` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=283 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

(Column `name` not null...)

**Comment by M3ndes** [comment]
Ok, it works now. 
I was not specifying the COLLATE utf8_unicode_ci. 
Started to work when i changed it.
 
 Thanks for the feedback.

**Comment by maurobonfietti** [comment]
Thank you for your report!
