### ISSUE TITLE
Data source not a table

### ISSUE THREAD

**Issue by StephanKrauss** [maurobonfietti/slim4-api-skeleton-crud-generator#8]
Hello  mauro,

I have a simple question. I will start a new project.
This project is a crud project.
Now for one controller the data source is not a table.
Is there a way to generate a new endpoint without database access.
I think to generate a new dummy repository file is the best way.

Can you help ?

Your sincerly

Stephan

>> Thanks for the video description

**Comment by maurobonfietti** [comment]
Hi Stephan!

If you already have a MySQL database, you can use this project to auto-generate CRUD endpoints for each of your tables.

For the other resource that the data source is not a table, I think you can do something like this:

**Update `Routes.php`:**

```php
$app->get('/resource', function ($request, $response) {
    // Your PHP Code Here...
});
```

Where "get" is the HTTP method that you need (like get, post, put, patch, delete, etc) and where "/resource" is the path to your endpoint, for example GET to "https://example.com/resource".

So, I think you can put your code there at least like an starting point.

----

Another option, depending of whatever you are developing, you can update the Routes.php and create a structure like this:

**Update `Routes.php`:**

```php
...
$app->get("/resource", "App\Controller\Foo");
...
```

**Create:**
```
src
├── Controller
│   ├── Foo.php
├── Repository
│   ├── Foo.php
└── Service
    ├── Foo.php
```

"Foo" is your resource where the data source is not a table.

----

**Summary:**

Yes, you have differents ways to create a new endpoint (even without database access) and you should do it manually.

For example, updating the file "Routes.php" and create the new endpoint inside an anonymous function.

Or else, creating the new endpoint using as many Controllers and Services as you need (even a Repository file if it make sense for this endpoint).

I hope it helps you in your project.

Best regards.
